/**
 * Seed script for populating the bookshelf with books.
 * Run: node server/bookshelf-seed.js
 */
require('./loadEnv');

const { createBookshelfEntry, ensureDatabase } = require('./db');

// ── Online books (from ebook files) ────────────────────────────────────────
const onlineBooks = [
  { title: '$100M Leads', author: 'Alex Hormozi', tags: ['business', 'marketing', 'sales'] },
  { title: 'Талановитий містер Ріплі', author: 'Патриція Гайсміт', tags: ['fiction', 'thriller'] },
  { title: '507 Mechanical Movements', author: 'Henry T. Brown', tags: ['engineering', 'reference'] },
  { title: 'A Beautiful Mind', author: 'Sylvia Nasar', tags: ['biography', 'mathematics', 'science'] },
  { title: 'A Brief Guide to Stephen King', author: 'Paul Simpson', tags: ['literature', 'reference'] },
  { title: 'A Brief History of Intelligence', author: 'Max Bennett', tags: ['science', 'neuroscience', 'AI'] },
  { title: 'A Man for All Markets', author: 'Edward O. Thorp', tags: ['finance', 'memoir', 'mathematics'] },
  { title: "A Mathematician's Apology", author: 'G. H. Hardy', tags: ['mathematics', 'philosophy'] },
  { title: 'A Mind at Play', author: 'Jimmy Soni & Rob Goodman', tags: ['biography', 'science', 'mathematics'] },
  { title: 'A Random Walk Down Wall Street', author: 'Burton G. Malkiel', tags: ['finance', 'investing'] },
  { title: "A Supposedly Fun Thing I'll Never Do Again", author: 'David Foster Wallace', tags: ['essays', 'literature'] },
  { title: 'A Time of Gifts', author: 'Patrick Leigh Fermor', tags: ['travel', 'memoir'] },
  { title: 'A Course in Game Theory', author: 'Martin J. Osborne & Ariel Rubinstein', tags: ['mathematics', 'economics', 'game theory'] },
  { title: 'A Sense of Urgency', author: 'John P. Kotter', tags: ['business', 'leadership'] },
  { title: 'Adaptive Markets', author: 'Andrew W. Lo', tags: ['finance', 'economics', 'science'] },
  { title: 'Advanced Microservices', author: 'Thomas Hunter II', tags: ['software engineering', 'architecture'] },
  { title: 'Against the Gods', author: 'Peter L. Bernstein', tags: ['finance', 'history', 'risk'] },
  { title: 'AiSDR Series A Memo', author: 'AiSDR Team', tags: ['startups', 'AI', 'business'] },
  { title: 'Notes on the Synthesis of Form', author: 'Christopher Alexander', tags: ['design', 'architecture', 'systems'] },
  { title: 'Apple in China', author: 'Patrick McGee', tags: ['business', 'technology', 'geopolitics'] },
  { title: 'Foundation', author: 'Isaac Asimov', tags: ['fiction', 'science fiction'] },
  { title: 'Baddest Man', author: 'Shing Yin Khor', tags: ['fiction', 'graphic novel'] },
  { title: 'Basic Economics', author: 'Thomas Sowell', tags: ['economics', 'education'] },
  { title: 'Be Not Afraid of Life', author: 'William James', tags: ['philosophy', 'self-help'] },
  { title: 'Benjamin Franklin: An American Life', author: 'Walter Isaacson', tags: ['biography', 'history'] },
  { title: 'Berkshire Hathaway Letters to Shareholders', author: 'Warren Buffett', tags: ['investing', 'business', 'finance'] },
  { title: 'Beyond Thoughts', author: 'Joseph Nguyen', tags: ['philosophy', 'self-help', 'mindfulness'] },
  { title: 'Blitzscaling', author: 'Reid Hoffman & Chris Yeh', tags: ['startups', 'business', 'technology'] },
  { title: 'Beyond Order', author: 'Jordan B. Peterson', tags: ['psychology', 'self-help', 'philosophy'] },
  { title: 'Brave New World', author: 'Aldous Huxley', tags: ['fiction', 'dystopia', 'classic'] },
  { title: 'Breakneck', author: 'Catherine Coulter', tags: ['fiction', 'thriller'] },
  { title: 'Building Microservices', author: 'Sam Newman', tags: ['software engineering', 'architecture'] },
  { title: 'Business Adventures', author: 'John Brooks', tags: ['business', 'finance', 'history'] },
  { title: 'Capital, Volume I', author: 'Karl Marx', tags: ['economics', 'philosophy', 'politics'] },
  { title: 'Careless People', author: 'Sarah Churchwell', tags: ['literature', 'history'] },
  { title: 'Chess Story', author: 'Stefan Zweig', tags: ['fiction', 'classic', 'chess'] },
  { title: 'Chokepoints', author: 'Edward Geist', tags: ['geopolitics', 'technology', 'economics'] },
  { title: 'Coders at Work', author: 'Peter Seibel', tags: ['software engineering', 'interviews'] },
  { title: 'Good to Great', author: 'Jim Collins', tags: ['business', 'leadership', 'management'] },
  { title: 'Conversations with God, Volume 3', author: 'Neale Donald Walsch', tags: ['spirituality', 'philosophy'] },
  { title: 'Creativity, Inc.', author: 'Ed Catmull & Amy Wallace', tags: ['business', 'creativity', 'leadership'] },
  { title: 'Damn Right!', author: 'Janet Lowe', tags: ['biography', 'investing', 'business'] },
  { title: 'Deep Learning', author: 'Ian Goodfellow, Yoshua Bengio & Aaron Courville', tags: ['AI', 'machine learning', 'computer science'] },
  { title: 'Deep Work', author: 'Cal Newport', tags: ['productivity', 'self-help'] },
  { title: 'Democracy in America', author: 'Alexis de Tocqueville', tags: ['politics', 'history', 'philosophy'] },
  { title: 'Designing Data-Intensive Applications', author: 'Martin Kleppmann', tags: ['software engineering', 'architecture', 'databases'] },
  { title: 'Disciplined Entrepreneurship Workbook', author: 'Bill Aulet', tags: ['startups', 'business', 'entrepreneurship'] },
  { title: 'Dive into Deep Learning', author: 'Aston Zhang, Zachary C. Lipton, Mu Li & Alexander J. Smola', tags: ['AI', 'machine learning', 'computer science'] },
  { title: "Don't Believe Everything You Think", author: 'Joseph Nguyen', tags: ['self-help', 'mindfulness', 'psychology'] },
  { title: 'Draft No. 4', author: 'John McPhee', tags: ['writing', 'essays'] },
  { title: 'Eat and Run', author: 'Scott Jurek', tags: ['memoir', 'sports', 'health'] },
  { title: 'Economics 101', author: 'Alfred Mill', tags: ['economics', 'education'] },
  { title: 'Engineering in Plain Sight', author: 'Grady Hillhouse', tags: ['engineering', 'science', 'infrastructure'] },
  { title: 'The Almanack of Naval Ravikant', author: 'Eric Jorgenson', tags: ['philosophy', 'business', 'self-help'] },
  { title: 'The Essays of Warren Buffett', author: 'Warren Buffett & Lawrence A. Cunningham', tags: ['investing', 'business', 'finance'] },
  { title: 'Essays', author: 'Michel de Montaigne', tags: ['philosophy', 'essays', 'classic'] },
  { title: 'Everything You Want Is on the Other Side of Hard', author: 'Alex Hormozi', tags: ['business', 'self-help', 'motivation'] },
  { title: 'Excellent Advice for Living', author: 'Kevin Kelly', tags: ['self-help', 'philosophy', 'wisdom'] },
  { title: 'Extreme Ownership', author: 'Jocko Willink & Leif Babin', tags: ['leadership', 'military', 'business'] },
  { title: 'F. Scott Fitzgerald on Writing', author: 'F. Scott Fitzgerald', tags: ['writing', 'literature'] },
  { title: 'FCO: Fundamental Chess Openings', author: 'Paul van der Sterren', tags: ['chess', 'reference'] },
  { title: 'Fahrenheit 451', author: 'Ray Bradbury', tags: ['fiction', 'dystopia', 'classic'] },
  { title: 'Fairy Tale', author: 'Stephen King', tags: ['fiction', 'fantasy'] },
  { title: "Fortune's Formula", author: 'William Poundstone', tags: ['finance', 'mathematics', 'history'] },
  { title: 'Games and Decisions', author: 'R. Duncan Luce & Howard Raiffa', tags: ['mathematics', 'game theory', 'economics'] },
  { title: 'Getting Things Done', author: 'David Allen', tags: ['productivity', 'self-help', 'business'] },
  { title: 'Good Strategy Bad Strategy', author: 'Richard Rumelt', tags: ['business', 'strategy'] },
  { title: 'Gödel, Escher, Bach: An Eternal Golden Braid', author: 'Douglas R. Hofstadter', tags: ['mathematics', 'philosophy', 'computer science'] },
  { title: 'Hackers & Painters', author: 'Paul Graham', tags: ['technology', 'essays', 'startups'] },
  { title: 'Hateship, Friendship, Courtship, Loveship, Marriage', author: 'Alice Munro', tags: ['fiction', 'short stories'] },
  { title: 'Hidden Systems', author: 'Dan Nott', tags: ['technology', 'infrastructure', 'graphic novel'] },
  { title: 'History Matters', author: 'Judith M. Bennett', tags: ['history', 'historiography'] },
  { title: 'House of Huawei', author: 'Eva Dou', tags: ['business', 'technology', 'geopolitics'] },
  { title: 'How I Won a Nobel Prize', author: 'Julius Taranto', tags: ['fiction', 'satire'] },
  { title: 'How I Read', author: 'Henrik Karlsson', tags: ['essays', 'reading', 'self-help'] },
  { title: 'How to Win Friends and Influence People', author: 'Dale Carnegie', tags: ['self-help', 'communication', 'classic'] },
  { title: 'How to Avoid a Climate Disaster', author: 'Bill Gates', tags: ['science', 'climate', 'technology'] },
  { title: 'How to Build a Billion Dollar Company', author: 'Various', tags: ['startups', 'business'] },
  { title: 'How to Create a Mind', author: 'Ray Kurzweil', tags: ['AI', 'neuroscience', 'technology'] },
  { title: 'How to Solve It', author: 'George Pólya', tags: ['mathematics', 'problem solving', 'education'] },
  { title: 'How the World Really Works', author: 'Vaclav Smil', tags: ['science', 'energy', 'economics'] },
  { title: 'How to Prevent the Next Pandemic', author: 'Bill Gates', tags: ['science', 'health', 'policy'] },
  { title: 'How to Read a Book', author: 'Mortimer J. Adler & Charles Van Doren', tags: ['education', 'reading', 'self-help'] },
  { title: 'I Am That', author: 'Sri Nisargadatta Maharaj', tags: ['spirituality', 'philosophy'] },
  { title: 'I Am a Strange Loop', author: 'Douglas R. Hofstadter', tags: ['philosophy', 'consciousness', 'mathematics'] },
  { title: 'Proofs and Refutations', author: 'Imre Lakatos', tags: ['mathematics', 'philosophy of science'] },
  { title: "In the Buddha's Words", author: 'Bhikkhu Bodhi', tags: ['spirituality', 'Buddhism', 'philosophy'] },
  { title: 'Into the Wild', author: 'Jon Krakauer', tags: ['memoir', 'adventure', 'nature'] },
  { title: 'Invent and Wander', author: 'Jeff Bezos & Walter Isaacson', tags: ['business', 'technology', 'biography'] },
  { title: 'Jack Welch GE Annual Letters', author: 'Jack Welch', tags: ['business', 'leadership', 'management'] },
  { title: 'The Remains of the Day', author: 'Kazuo Ishiguro', tags: ['fiction', 'classic', 'literature'] },
  { title: 'Kissinger', author: 'Walter Isaacson', tags: ['biography', 'politics', 'history'] },
  { title: 'Klara and the Sun', author: 'Kazuo Ishiguro', tags: ['fiction', 'AI', 'literature'] },
  { title: 'Kleptopia', author: 'Tom Burgis', tags: ['politics', 'finance', 'investigative'] },
  { title: 'Kubernetes: Up and Running', author: 'Brendan Burns, Joe Beda & Kelsey Hightower', tags: ['software engineering', 'DevOps', 'cloud'] },
  { title: 'Lab Girl', author: 'Hope Jahren', tags: ['memoir', 'science'] },
  { title: "Leaving Isn't the Hardest Thing", author: 'Lauren Hough', tags: ['memoir', 'essays'] },
  { title: 'Leonardo da Vinci', author: 'Walter Isaacson', tags: ['biography', 'art', 'history'] },
  { title: 'Lessons of History', author: 'Will Durant & Ariel Durant', tags: ['history', 'philosophy'] },
  { title: 'Letters from a Stoic', author: 'Seneca', tags: ['philosophy', 'Stoicism', 'classic'] },
  { title: 'Life Is a Miracle', author: 'Wendell Berry', tags: ['philosophy', 'nature', 'essays'] },
  { title: 'Market Wizards', author: 'Jack D. Schwager', tags: ['finance', 'investing', 'interviews'] },
  { title: 'Marketing Moonshots', author: 'Tom Orbach', tags: ['marketing', 'business'] },
  { title: 'Mathematics for Computer Science', author: 'Eric Lehman, F. Thomson Leighton & Albert R. Meyer', tags: ['mathematics', 'computer science'] },
  { title: 'Play Nice But Win', author: 'Michael Dell', tags: ['biography', 'business', 'technology'] },
  { title: 'Modern Chess Openings', author: 'Nick de Firmian', tags: ['chess', 'reference'] },
  { title: 'My 60 Memorable Games', author: 'Bobby Fischer', tags: ['chess', 'memoir'] },
  { title: 'Narrative Economics', author: 'Robert J. Shiller', tags: ['economics', 'finance', 'behavioral science'] },
  { title: 'Nicomachean Ethics', author: 'Aristotle', tags: ['philosophy', 'ethics', 'classic'] },
  { title: 'Nine Things I Learned in Ninety Years', author: 'Henry Kissinger', tags: ['memoir', 'politics', 'wisdom'] },
  { title: 'No Country for Old Men', author: 'Cormac McCarthy', tags: ['fiction', 'thriller', 'literature'] },
  { title: 'No Filter: The Inside Story of Instagram', author: 'Sarah Frier', tags: ['business', 'technology', 'social media'] },
  { title: "Nobody's Girl", author: 'Hector Malot', tags: ['fiction', 'classic'] },
  { title: 'On Writing Well', author: 'William Zinsser', tags: ['writing', 'education'] },
  { title: 'On the Measure of Intelligence', author: 'François Chollet', tags: ['AI', 'computer science', 'research'] },
  { title: 'On the Origin of Species', author: 'Charles Darwin', tags: ['science', 'biology', 'classic'] },
  { title: 'On the Road', author: 'Jack Kerouac', tags: ['fiction', 'classic', 'literature'] },
  { title: 'One Thousand Ways to Make $1000', author: 'F. C. Minaker', tags: ['business', 'finance', 'classic'] },
  { title: 'Only the Paranoid Survive', author: 'Andrew S. Grove', tags: ['business', 'technology', 'leadership'] },
  { title: 'Open: An Autobiography', author: 'Andre Agassi', tags: ['memoir', 'sports'] },
  { title: 'Operating Systems: Three Easy Pieces', author: 'Remzi H. Arpaci-Dusseau & Andrea C. Arpaci-Dusseau', tags: ['computer science', 'operating systems'] },
  { title: 'Outlive', author: 'Peter Attia', tags: ['health', 'science', 'longevity'] },
  { title: 'Outside the Box', author: 'Marc Levinson', tags: ['business', 'history', 'economics'] },
  { title: 'The Outsider', author: 'Albert Camus', tags: ['fiction', 'philosophy', 'classic'] },
  { title: 'Patriot', author: 'Alexei Navalny', tags: ['memoir', 'politics', 'history'] },
  { title: 'Permanent Record', author: 'Edward Snowden', tags: ['memoir', 'technology', 'politics'] },
  { title: 'Positioning', author: 'Al Ries & Jack Trout', tags: ['marketing', 'business'] },
  { title: 'Possession', author: 'A. S. Byatt', tags: ['fiction', 'literature'] },
  { title: 'Pre-Suasion', author: 'Robert Cialdini', tags: ['psychology', 'marketing', 'persuasion'] },
  { title: 'Principles', author: 'Ray Dalio', tags: ['business', 'philosophy', 'investing'] },
  { title: 'Project Hail Mary', author: 'Andy Weir', tags: ['fiction', 'science fiction'] },
  { title: 'Proof or Bluff: Evaluating LLMs on 2025 USA Math Olympiad', author: 'Various Researchers', tags: ['AI', 'mathematics', 'research'] },
  { title: 'Purpose and Profit', author: 'Dan Koe', tags: ['business', 'self-help', 'entrepreneurship'] },
  { title: 'Quantum Computation and Quantum Information', author: 'Michael A. Nielsen & Isaac L. Chuang', tags: ['physics', 'computer science', 'quantum'] },
  { title: 'Reality Is Not What It Seems', author: 'Carlo Rovelli', tags: ['physics', 'science', 'philosophy'] },
  { title: 'Reentry', author: 'Eric Berger', tags: ['biography', 'technology', 'space'] },
  { title: 'Reminiscences of a Stock Operator', author: 'Edwin Lefèvre', tags: ['finance', 'investing', 'classic'] },
  { title: 'The Path of Least Resistance', author: 'Robert Fritz', tags: ['creativity', 'self-help', 'philosophy'] },
  { title: 'Seeing Like a State', author: 'James C. Scott', tags: ['politics', 'history', 'economics'] },
  { title: 'Self-Reliance and Other Essays', author: 'Ralph Waldo Emerson', tags: ['philosophy', 'essays', 'classic'] },
  { title: 'Shoe Dog', author: 'Phil Knight', tags: ['memoir', 'business', 'entrepreneurship'] },
  { title: 'How to Live', author: 'Derek Sivers', tags: ['philosophy', 'self-help'] },
  { title: 'Hell Yeah or No', author: 'Derek Sivers', tags: ['self-help', 'philosophy', 'essays'] },
  { title: 'Six Stories', author: 'Matt Wesolowski', tags: ['fiction', 'thriller', 'mystery'] },
  { title: 'Softwar', author: 'Matthew Symonds', tags: ['biography', 'business', 'technology'] },
  { title: 'Software Architecture in Practice', author: 'Len Bass, Paul Clements & Rick Kazman', tags: ['software engineering', 'architecture'] },
  { title: 'Software Architecture Patterns', author: 'Mark Richards', tags: ['software engineering', 'architecture'] },
  { title: 'Spare', author: 'Prince Harry', tags: ['memoir', 'politics'] },
  { title: 'Staff Engineer', author: 'Will Larson', tags: ['software engineering', 'leadership', 'career'] },
  { title: 'State of AI SDR Industry 2026', author: 'AiSDR Team', tags: ['AI', 'business', 'research'] },
  { title: 'Streetwise', author: 'Elijah Anderson', tags: ['sociology', 'urban studies'] },
  { title: 'Superforecasting', author: 'Philip E. Tetlock & Dan Gardner', tags: ['psychology', 'decision making', 'science'] },
  { title: 'Superintelligence', author: 'Nick Bostrom', tags: ['AI', 'philosophy', 'technology'] },
  { title: 'Sybil', author: 'Flora Rheta Schreiber', tags: ['psychology', 'biography'] },
  { title: 'System Design and Architecture', author: 'Various', tags: ['software engineering', 'architecture'] },
  { title: 'System Design Interview', author: 'Alex Xu', tags: ['software engineering', 'interviews', 'architecture'] },
  { title: 'The Varieties of Religious Experience', author: 'William James', tags: ['philosophy', 'religion', 'psychology'] },
  { title: 'Talking to Strangers', author: 'Malcolm Gladwell', tags: ['psychology', 'sociology'] },
  { title: 'Tao Te Ching', author: 'Lao Tzu', tags: ['philosophy', 'spirituality', 'classic'] },
  { title: 'Ted Williams: The Story of My Life', author: 'Ted Williams & John Underwood', tags: ['memoir', 'sports'] },
  { title: 'The $150M Secrets', author: 'Guillaume Moubeche', tags: ['startups', 'business', 'entrepreneurship'] },
  { title: 'The 38 Letters from J.D. Rockefeller to His Son', author: 'J.D. Rockefeller', tags: ['business', 'wisdom', 'classic'] },
  { title: 'The AI Scientist', author: 'Various Researchers', tags: ['AI', 'research', 'science'] },
  { title: 'The Alchemy of Finance', author: 'George Soros', tags: ['finance', 'investing', 'economics'] },
  { title: 'The Art of Learning', author: 'Josh Waitzkin', tags: ['self-help', 'chess', 'learning'] },
  { title: 'The Art of the Deal', author: 'Donald Trump & Tony Schwartz', tags: ['business', 'memoir'] },
  { title: 'The Autobiography of Malcolm X', author: 'Malcolm X & Alex Haley', tags: ['biography', 'history', 'politics'] },
  { title: 'The Beginning of Infinity', author: 'David Deutsch', tags: ['philosophy', 'science', 'physics'] },
  { title: 'The Body', author: 'Bill Bryson', tags: ['science', 'health', 'biology'] },
  { title: 'The Book of Why', author: 'Judea Pearl & Dana Mackenzie', tags: ['science', 'statistics', 'AI'] },
  { title: 'The Burning Earth', author: 'Sumanth Ramaswamy', tags: ['history', 'science'] },
  { title: 'The Checklist Manifesto', author: 'Atul Gawande', tags: ['productivity', 'health', 'business'] },
  { title: 'The Code Book', author: 'Simon Singh', tags: ['mathematics', 'cryptography', 'history'] },
  { title: 'The Code Breaker', author: 'Walter Isaacson', tags: ['biography', 'science', 'genetics'] },
  { title: 'The Complete Essays', author: 'Michel de Montaigne', tags: ['philosophy', 'essays', 'classic'] },
  { title: 'The Computer and the Brain', author: 'John von Neumann', tags: ['computer science', 'neuroscience', 'classic'] },
  { title: 'The Culture Code', author: 'Daniel Coyle', tags: ['business', 'leadership', 'psychology'] },
  { title: 'The Denial of Death', author: 'Ernest Becker', tags: ['philosophy', 'psychology'] },
  { title: 'The Descent of Man', author: 'Grayson Perry', tags: ['sociology', 'masculinity', 'art'] },
  { title: 'The Design of Everyday Things', author: 'Don Norman', tags: ['design', 'psychology', 'technology'] },
  { title: 'The Double Helix', author: 'James D. Watson', tags: ['science', 'biography', 'genetics'] },
  { title: 'The Elephant in the Brain', author: 'Kevin Simler & Robin Hanson', tags: ['psychology', 'philosophy', 'behavioral science'] },
  { title: 'The Fabric of Reality', author: 'David Deutsch', tags: ['physics', 'philosophy', 'science'] },
  { title: 'The Future Is History', author: 'Masha Gessen', tags: ['history', 'politics', 'Russia'] },
  { title: 'The Great CEO Within', author: 'Matt Mochary', tags: ['business', 'leadership', 'startups'] },
  { title: 'The Greatest Sentence Ever Written', author: 'Brian Garfield', tags: ['writing', 'literature'] },
  { title: 'The HP Way', author: 'David Packard', tags: ['business', 'technology', 'memoir'] },
  { title: 'The Infinity Machine', author: 'Nitasha Tiku', tags: ['technology', 'AI'] },
  { title: 'The Institute', author: 'Stephen King', tags: ['fiction', 'thriller'] },
  { title: 'The Interpretation of Dreams', author: 'Sigmund Freud', tags: ['psychology', 'classic', 'philosophy'] },
  { title: 'The Invisible Man', author: 'H. G. Wells', tags: ['fiction', 'science fiction', 'classic'] },
  { title: 'The Kiss', author: 'Kathryn Harrison', tags: ['memoir', 'literature'] },
  { title: 'The Last Economy', author: 'Emad Mostaque', tags: ['AI', 'economics', 'technology'] },
  { title: 'The Man Who Knew Infinity', author: 'Robert Kanigel', tags: ['biography', 'mathematics'] },
  { title: 'The Memoirs of the Dean of Wall Street', author: 'Benjamin Graham', tags: ['finance', 'memoir', 'investing'] },
  { title: 'The Mormon Way of Doing Business', author: 'Jeff Benedict', tags: ['business', 'religion', 'leadership'] },
  { title: 'The Most Important Thing', author: 'Howard Marks', tags: ['investing', 'finance'] },
  { title: 'The New Tao of Warren Buffett', author: 'Mary Buffett & David Clark', tags: ['investing', 'wisdom', 'business'] },
  { title: 'The Optimist', author: 'David Coggins', tags: ['essays', 'culture'] },
  { title: 'The Parasitic Mind', author: 'Gad Saad', tags: ['psychology', 'politics', 'philosophy'] },
  { title: 'The Philosopher in the Valley', author: 'Various', tags: ['philosophy', 'technology', 'essays'] },
  { title: 'The Power Broker', author: 'Robert A. Caro', tags: ['biography', 'politics', 'history'] },
  { title: 'The Prince and Other Writings', author: 'Niccolò Machiavelli', tags: ['philosophy', 'politics', 'classic'] },
  { title: 'The Product-Minded Engineer', author: 'Various', tags: ['software engineering', 'product', 'career'] },
  { title: 'The Psychology of Money', author: 'Morgan Housel', tags: ['finance', 'psychology', 'investing'] },
  { title: 'The Rational Optimist', author: 'Matt Ridley', tags: ['economics', 'science', 'history'] },
  { title: 'The Republic', author: 'Plato', tags: ['philosophy', 'politics', 'classic'] },
  { title: 'The Righteous Mind', author: 'Jonathan Haidt', tags: ['psychology', 'politics', 'philosophy'] },
  { title: 'The Selfish Gene', author: 'Richard Dawkins', tags: ['science', 'biology', 'evolution'] },
  { title: 'The Simple Path to Wealth', author: 'JL Collins', tags: ['finance', 'investing', 'self-help'] },
  { title: 'The Sleepwalkers', author: 'Christopher Clark', tags: ['history', 'war', 'politics'] },
  { title: 'The Toyota Way', author: 'Jeffrey K. Liker', tags: ['business', 'management', 'manufacturing'] },
  { title: 'The Writer Who Stayed', author: 'William Zinsser', tags: ['writing', 'essays'] },
  { title: 'The Anthology of Balaji', author: 'Balaji Srinivasan', tags: ['technology', 'startups', 'philosophy'] },
  { title: 'The Value of Everything', author: 'Mariana Mazzucato', tags: ['economics', 'politics', 'philosophy'] },
  { title: 'The Man Who Loved Only Numbers', author: 'Paul Hoffman', tags: ['biography', 'mathematics'] },
  { title: 'The Man from the Future', author: 'Ananyo Bhattacharya', tags: ['biography', 'mathematics', 'science'] },
  { title: 'Theory of Games and Economic Behavior', author: 'John von Neumann & Oskar Morgenstern', tags: ['mathematics', 'economics', 'game theory'] },
  { title: 'Theory of Self-Reproducing Automata', author: 'John von Neumann', tags: ['computer science', 'mathematics', 'classic'] },
  { title: 'Things in Nature Merely Grow', author: 'Various', tags: ['nature', 'philosophy', 'essays'] },
  { title: 'Think on These Things', author: 'Jiddu Krishnamurti', tags: ['philosophy', 'spirituality', 'education'] },
  { title: 'Thinking in Bets', author: 'Annie Duke', tags: ['psychology', 'decision making', 'business'] },
  { title: 'Titan', author: 'Ron Chernow', tags: ['biography', 'business', 'history'] },
  { title: 'To Kill a Mockingbird', author: 'Harper Lee', tags: ['fiction', 'classic', 'literature'] },
  { title: 'Tools of Titans', author: 'Tim Ferriss', tags: ['self-help', 'business', 'interviews'] },
  { title: 'Trust', author: 'Hernán Díaz', tags: ['fiction', 'literature'] },
  { title: 'Vehicles: Experiments in Synthetic Psychology', author: 'Valentino Braitenberg', tags: ['AI', 'psychology', 'science'] },
  { title: 'Walden', author: 'Henry David Thoreau', tags: ['philosophy', 'nature', 'classic'] },
  { title: 'War and Peace', author: 'Leo Tolstoy', tags: ['fiction', 'classic', 'literature'] },
  { title: 'Why I Write', author: 'George Orwell', tags: ['writing', 'essays', 'literature'] },
  { title: 'Why Nations Fail', author: 'Daron Acemoglu & James A. Robinson', tags: ['economics', 'politics', 'history'] },
  { title: 'Writing Places', author: 'William Zinsser', tags: ['writing', 'memoir'] },
  { title: 'Writing Tips', author: 'Scott Adams', tags: ['writing', 'self-help'] },
  { title: 'Writing to Learn', author: 'William Zinsser', tags: ['writing', 'education'] },
  { title: 'Your Life Is Manufactured', author: 'Tim Minshall', tags: ['engineering', 'manufacturing', 'education'] },
  { title: 'Writing About Your Life', author: 'William Zinsser', tags: ['writing', 'memoir'] },
  { title: "Clay's Operating Principles", author: 'Various', tags: ['business', 'startups'] },
  { title: 'Founders at Work', author: 'Jessica Livingston', tags: ['startups', 'interviews', 'technology'] },
  { title: 'The Diary of a Young Girl', author: 'Anne Frank', tags: ['memoir', 'history', 'classic'] },
  { title: 'How Fascism Works', author: 'Jason Stanley', tags: ['politics', 'history', 'philosophy'] },
  { title: 'Introduction to Classical and Quantum Computing', author: 'Thomas G. Wong', tags: ['computer science', 'quantum', 'physics'] },
  { title: 'Isaac Newton', author: 'James Gleick', tags: ['biography', 'science', 'history'] },
  { title: "I've Been Thinking...", author: 'Maria Shriver', tags: ['memoir', 'self-help'] },
  { title: 'Jack Welch Speaks', author: 'Janet Lowe', tags: ['business', 'leadership'] },
  { title: 'Laws of Economics', author: 'Various', tags: ['economics', 'education'] },
  { title: 'Intermediate Microeconomics', author: 'Hal R. Varian', tags: ['economics', 'education'] },
  { title: 'Neural Networks and Deep Learning', author: 'Michael Nielsen', tags: ['AI', 'machine learning', 'computer science'] },
  { title: 'On the Shortness of Life', author: 'Seneca', tags: ['philosophy', 'Stoicism', 'classic'] },
  { title: 'Capital in the Twenty-First Century', author: 'Thomas Piketty', tags: ['economics', 'politics', 'history'] },
  { title: 'Raw Thought', author: 'Aaron Swartz', tags: ['technology', 'essays', 'politics'] },
  { title: 'Situational Awareness', author: 'Leopold Aschenbrenner', tags: ['AI', 'technology', 'geopolitics'] },
  { title: 'The Architect of Berkshire Hathaway', author: 'Various', tags: ['investing', 'biography', 'business'] },
  { title: 'The Art of Profitability', author: 'Adrian Slywotzky', tags: ['business', 'strategy'] },
  { title: 'The Brain from Inside Out', author: 'György Buzsáki', tags: ['neuroscience', 'science'] },
  { title: 'The Story of My Life', author: 'Helen Keller', tags: ['memoir', 'biography', 'classic'] },
  { title: 'The Visual Display of Quantitative Information', author: 'Edward R. Tufte', tags: ['design', 'data visualization', 'statistics'] },
  { title: 'The Gifts of Imperfection', author: 'Brené Brown', tags: ['self-help', 'psychology'] },
  { title: 'The Stranger in the Woods', author: 'Michael Finkel', tags: ['memoir', 'nature'] },
  { title: 'The Wealth of Nations', author: 'Adam Smith', tags: ['economics', 'classic', 'philosophy'] },
  { title: 'Воєнні мемуари, Том 1', author: 'Шарль де Голль', tags: ['memoir', 'history', 'war'] },
  { title: 'Гемінґвей нічого не знає', author: 'Сергій Жадан', tags: ['fiction', 'Ukrainian literature'] },
  { title: 'Чайка Джонатан Лівінгстон', author: 'Річард Бах', tags: ['fiction', 'philosophy', 'fable'] },
  { title: 'LDL Sample', author: 'Various', tags: ['health', 'science'] },
];

// ── Physical books (not online) ────────────────────────────────────────────
// Deduplicated. Ukrainian authors keep Ukrainian titles.
const physicalBooks = [
  { title: 'On Writing: A Memoir of the Craft', author: 'Stephen King', tags: ['writing', 'memoir'] },
  { title: 'Doctor Sleep', author: 'Stephen King', tags: ['fiction', 'horror'] },
  { title: 'Стрілець', author: 'Стівен Кінг', tags: ['fiction', 'fantasy', 'classic'] },
  { title: 'Зелена миля', author: 'Стівен Кінг', tags: ['fiction', 'classic'] },
  { title: 'Sapiens: A Brief History of Humankind', author: 'Yuval Noah Harari', tags: ['history', 'science', 'philosophy'] },
  { title: 'This Is Marketing', author: 'Seth Godin', tags: ['marketing', 'business'] },
  { title: 'On Freedom', author: 'Timothy Snyder', tags: ['politics', 'philosophy', 'history'] },
  { title: 'Zero to One', author: 'Peter Thiel & Blake Masters', tags: ['startups', 'business', 'technology'] },
  { title: 'Hooked', author: 'Nir Eyal', tags: ['product', 'psychology', 'business'] },
  { title: 'iWoz', author: 'Steve Wozniak & Gina Smith', tags: ['biography', 'technology'] },
  { title: 'Brief Answers to the Big Questions', author: 'Stephen Hawking', tags: ['science', 'physics', 'philosophy'] },
  { title: 'Страшенно голосно і неймовірно близько', author: 'Джонатан Сафран Фоер', tags: ['fiction', 'literature'] },
  { title: 'Чудове подружжя', author: 'Кімберлі Маккрейт', tags: ['fiction', 'thriller'] },
  { title: 'Каста', author: 'Ізабель Вілкерсон', tags: ['sociology', 'history', 'politics'] },
  { title: 'Розум. Убивці', author: 'Майк Омер', tags: ['fiction', 'thriller'] },
  { title: 'Смажені зелені помідори в кафе «Зупинка»', author: 'Фенні Флегг', tags: ['fiction', 'classic'] },
  { title: 'Санаторій', author: 'Сара Пірс', tags: ['fiction', 'thriller'] },
  { title: '4000 тижнів', author: 'Олівер Беркеман', tags: ['productivity', 'philosophy', 'self-help'] },
  { title: 'Стрімголов: історія одного життя', author: 'Олівер Сакс', tags: ['memoir', 'science', 'neuroscience'] },
  { title: 'Книга в камені', author: 'Юрій Даценко', tags: ['Ukrainian literature', 'history'] },
  { title: 'The Innovators', author: 'Walter Isaacson', tags: ['biography', 'technology', 'history'] },
  { title: 'Elon Musk', author: 'Ashlee Vance', tags: ['biography', 'technology', 'business'] },
  { title: 'Bill Gates: Source Code', author: 'Various', tags: ['biography', 'technology'] },
  { title: 'Broken Code', author: 'Jeff Horwitz', tags: ['technology', 'social media', 'investigative'] },
  { title: 'Моє життя та робота', author: 'Генрі Форд', tags: ['biography', 'business', 'classic'] },
  { title: 'The Everything Store', author: 'Brad Stone', tags: ['biography', 'business', 'technology'] },
  { title: 'Переломний рік', author: 'Бріанна Вієст', tags: ['self-help', 'philosophy'] },
  { title: 'Мрії мого батька', author: 'Барак Обама', tags: ['memoir', 'politics'] },
  { title: 'Нові стоїки', author: 'Массімо Пільюччі & Ґреґорі Лопез', tags: ['philosophy', 'Stoicism', 'self-help'] },
  { title: 'Netflix і культура інновацій', author: 'Рід Гастінгс & Ерін Меєр', tags: ['business', 'leadership', 'management'] },
  { title: 'Людина, яка померла двічі', author: 'Річард Осман', tags: ['fiction', 'mystery'] },
  { title: 'Tesla: Винахідник сучасності', author: 'Річард Мансон', tags: ['biography', 'science', 'technology'] },
  { title: 'Не озирайся і мовчи', author: 'Макс Кідрук', tags: ['fiction', 'Ukrainian literature', 'thriller'] },
  { title: 'Таємниця старого Лами', author: 'Дорж Бату', tags: ['fiction', 'spirituality'] },
  { title: 'Діалоги', author: 'Платон', tags: ['philosophy', 'classic'] },
  { title: 'Таємнича історія Біллі Міллігана', author: 'Деніел Кіз', tags: ['psychology', 'biography'] },
  { title: 'Testing with Humans', author: 'Giff Constable & Frank Rimalovski', tags: ['product', 'startups', 'design'] },
  { title: 'The War for Reality', author: 'Dmytro Kuleba', tags: ['politics', 'geopolitics', 'Ukraine'] },
  { title: 'Грішна', author: 'Тесс Ґеррітсен', tags: ['fiction', 'thriller'] },
  { title: 'Dunbar', author: 'Edward St Aubyn', tags: ['fiction', 'literature'] },
  { title: 'Діви', author: 'Алекс Міхаелідес', tags: ['fiction', 'thriller', 'mystery'] },
  { title: 'Думати, як Зигмунд Фрейд', author: 'Деніел Сміт', tags: ['psychology', 'philosophy'] },
  { title: 'Блокчейн-революція', author: 'Дон Тапскотт & Алекс Тапскотт', tags: ['technology', 'finance', 'business'] },
  { title: 'Бог завжди подорожує інкогніто', author: 'Лоран Ґунель', tags: ['fiction', 'self-help'] },
  { title: 'Есенціалізм', author: 'Ґреґ МакКіон', tags: ['productivity', 'self-help', 'business'] },
  { title: 'Черчилль і Орвелл', author: 'Томас Рікс', tags: ['biography', 'history', 'politics'] },
  { title: 'Список запрошених', author: 'Люсі Фолі', tags: ['fiction', 'thriller', 'mystery'] },
  { title: '48 законів влади', author: 'Роберт Ґрін', tags: ['psychology', 'politics', 'self-help'] },
  { title: 'Пікассо: живопис, що шокував світ', author: 'Майлз Дж. Ангер', tags: ['biography', 'art'] },
  { title: 'Tribe of Mentors', author: 'Tim Ferriss', tags: ['self-help', 'interviews', 'business'] },
  { title: 'Will', author: 'Will Smith & Mark Manson', tags: ['memoir', 'entertainment'] },
  { title: 'Nine Perfect Strangers', author: 'Liane Moriarty', tags: ['fiction', 'thriller'] },
  { title: 'Правила гри', author: 'Ніл Стросс', tags: ['self-help', 'psychology'] },
  { title: 'Філософія: 50 видатних творів', author: 'Том Батлер-Боудон', tags: ['philosophy', 'reference'] },
  { title: 'The Ultimate Finance Book', author: 'Roger Mason et al.', tags: ['finance', 'education'] },
  { title: '250 фішок для письменників', author: 'Чак Вендіг', tags: ['writing', 'reference'] },
  { title: 'The Club: Мистецтво об\'єднувати', author: 'Сергій Гайдай', tags: ['Ukrainian literature', 'business'] },
  { title: 'Автобіографія', author: 'Ендрю Карнегі', tags: ['biography', 'business', 'classic'] },
  { title: 'A Storm of Swords', author: 'George R. R. Martin', tags: ['fiction', 'fantasy'] },
  { title: 'Монах, який продав свій «Ferrari»', author: 'Робін Шарма', tags: ['self-help', 'fiction', 'philosophy'] },
  { title: 'Справа Василя Стуса', author: 'Вахтанг Кіпіані', tags: ['Ukrainian literature', 'history', 'politics'] },
  { title: 'Steve Jobs', author: 'Walter Isaacson', tags: ['biography', 'technology', 'business'] },
  { title: '101 есеїв, які змінять ваше мислення', author: 'Бріанна Вієст', tags: ['self-help', 'essays', 'philosophy'] },
  { title: 'An Elegant Puzzle', author: 'Will Larson', tags: ['software engineering', 'management', 'leadership'] },
  { title: 'Never Split the Difference', author: 'Chris Voss & Tahl Raz', tags: ['negotiation', 'business', 'psychology'] },
  { title: "Poor Charlie's Almanack", author: 'Peter D. Kaufman (ed.)', tags: ['investing', 'wisdom', 'business'] },
  { title: 'Scaling People', author: 'Claire Hughes Johnson', tags: ['management', 'leadership', 'business'] },
  { title: 'Start With Why', author: 'Simon Sinek', tags: ['leadership', 'business', 'motivation'] },
  { title: 'The Art of Doing Science and Engineering', author: 'Richard W. Hamming', tags: ['science', 'engineering', 'education'] },
  { title: 'The Big Score', author: 'Michael S. Malone', tags: ['technology', 'history', 'business'] },
  { title: 'The Intelligent Investor', author: 'Benjamin Graham', tags: ['investing', 'finance', 'classic'] },
  { title: 'The Long Walk', author: 'Stephen King', tags: ['fiction', 'dystopia'] },
  { title: 'The Making of Prince of Persia', author: 'Jordan Mechner', tags: ['memoir', 'game design', 'technology'] },
  { title: 'The Power of Now', author: 'Eckhart Tolle', tags: ['spirituality', 'self-help', 'mindfulness'] },
  { title: 'The Snowball', author: 'Alice Schroeder', tags: ['biography', 'investing', 'business'] },
  { title: 'Winston Churchill CEO', author: 'Alan Axelrod', tags: ['biography', 'leadership', 'history'] },
  { title: 'Білий попіл', author: 'Іларіон Павлюк', tags: ['fiction', 'Ukrainian literature'] },
  { title: 'На Західному фронті без змін', author: 'Еріх Марія Ремарк', tags: ['fiction', 'war', 'classic'] },
  { title: 'Емоція за дизайном', author: 'Ґреґ Гоффман', tags: ['design', 'business', 'marketing'] },
  { title: 'Сяйво', author: 'Стівен Кінг', tags: ['fiction', 'horror', 'classic'] },
  { title: 'Як перекласти життя на сценарій', author: 'Антоніо Лукіч', tags: ['Ukrainian literature', 'film', 'memoir'] },
];

async function seed() {
  await ensureDatabase();

  const allBooks = [
    ...onlineBooks.map((b) => ({ ...b, isOnline: true })),
    ...physicalBooks.map((b) => ({ ...b, isOnline: false })),
  ];

  console.log(`Seeding ${allBooks.length} books (${onlineBooks.length} online, ${physicalBooks.length} physical)...`);
  let created = 0;
  let errors = 0;

  for (const book of allBooks) {
    try {
      await createBookshelfEntry({
        title: book.title,
        author: book.author,
        status: 'backlog',
        isOnline: book.isOnline,
        url: null,
        sortOrder: 0,
        tags: book.tags,
      });
      created++;
      if (created % 25 === 0) {
        console.log(`  ...created ${created} books`);
      }
    } catch (err) {
      errors++;
      console.error(`  FAILED: "${book.title}" — ${err.message}`);
    }
  }

  console.log(`\nDone. Created: ${created}, Errors: ${errors}`);
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
